### ISSUE TITLE
MILENAGE

### ISSUE THREAD

**Issue by kschepps** [GSMATerminals/Generic-eUICC-Test-Profile-for-Device-Testing-Public#3]
Is it possible for someone smarter than me to create an Open Source eSIM profile with MILENAGE algorithm?

**Comment by laf0rge** [comment]
Can you explain what you're trying to do?  Do you simply want a profile UPP (unprotected profile package) like the .der files here in this TS.48 repo?  I can easily take any of the profiles, e.g. TS48v5_SAIP2.1B_NoBERTLV.der and change it from XOR-3G to MILENAGE if you'd like.  But in order to do anythin with th eUPP You do have a way to sign that profile with key material that is accepted by your eUICC, as well as a SM-DP+ or a simulator thereof.

You may be interested in the recent minimalistic open source SM-DP+ implementatoin [osmo-smdpp](https://downloads.osmocom.org/docs/pysim/master/html/osmo-smdpp.html)

**Comment by kschepps** [comment]
Sorry, I forgot I posted this question. 

I was trying to get an eSIM solution. I changed the environment to support XOR. I don't need a Milinage test eSIM anymore. 

I'll close this issue.
